### ISSUE TITLE
add root

### ISSUE THREAD

**Issue by xtreemrage** [DannyMoerkerke/postbuild#2] opened 2016-06-27 12:41 UTC
Can you add an options to use a a root for the folder with the `-c` and `-j` tags. 
My npm script: 
```javascript
postbuild -i app/index.html -o dist/index.html -c app/assets/css
```
I have a project structure like this:

    .
    ├──  app
    │   ├── index.html
    │   ├── bower_components
    │   ├── default // this is a dummy folder, local development only
    │   ├── assets
    │   │ 	├── css
    │   │ 	│	└── custom.css
    ├── package.json
    └── package.json

To use the `-c` flag I need to define it like this: `-c app/assets/css`, and it will output my css in my index.html like this:

```html
<link rel="stylesheet" href="app/assets/css/animations.css">
```

But this is what I need (in my scenario):

```html
<link rel="stylesheet" href="assets/css/animations.css">
```

Maybe introduce in `-s` (source) flag, where you set your root folder?
```javascript
postbuild -i app/index.html -o dist/index.html -s app -c assets/css
```

**Comment by xtreemrage** [comment] 2016-08-15 07:54
@DannyMoerkerke is this package still maintained?

**Comment by DannyMoerkerke** [comment] 2016-08-15 18:19
Yes it is. Sorry for not replying, I missed it due to holidays. I get back to you asap.

**Comment by DannyMoerkerke** [comment] 2016-09-05 09:50
@xtreemrage I just merged a pull request which adds the `-g` option, this allows you to strip a prefix from the injected path.
So adding `-g app/` should do the trick for you.

**Closed by DannyMoerkerke** 2016-09-05 09:50 UTC

**Comment by joseika** [comment] 2017-11-10 12:55
Hi, I'm testing postbuild with npm scripts to inject js and css bundles into a base html template. The problem is that the injected urls are not relative to root, so they only work 1 place in the url hierarchy of our site. 
Adding "../" or "/" to the path fails, and I cannot get the -g option to do any good.
There should be an option, as @xtreemrage suggests, to define a root or prefix to the output url. 

Otherwise it works great, thanks!
